# Generated by Django 5.0.1 on 2024-01-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0004_alter_jeudeplateau_createur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='emprunteur',
        ),
    ]
