# Generated by Django 5.0.1 on 2024-01-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0011_alter_emprunt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nombreEmprunts',
            field=models.IntegerField(default=0),
        ),
    ]
