# Generated by Django 5.0.1 on 2024-01-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0014_alter_emprunt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_emprunts',
            field=models.DateField(null=True),
        ),
    ]
